---
- hosts: all
  become: yes
  tasks:
    - name: Ensure that apache web server is installed
      yum: #name=httpd state=present 
        name: httpd 
        state: present 
    - name: Ensure that is running and persistent
      service:
        name: httpd
        state: started
        enabled: yes
